import { useEffect, useState } from "react";
import { ExternalLink, RotateCcw } from "lucide-react";
import { fetchSellerReturns, updateSellerReturn, type SellerReturnRequest } from "../../api/seller";
import { useToast } from "../../components/ToastProvider";

const NEXT: Record<string, string[]> = { requested: ["under_review", "approved", "rejected"], under_review: ["approved", "rejected"], approved: ["return_in_transit"], return_in_transit: ["received"], received: ["refunded"], refunded: ["closed"] };

export default function SellerReturnsPage() {
  const { showToast } = useToast();
  const [returns, setReturns] = useState<SellerReturnRequest[]>([]);
  const [responses, setResponses] = useState<Record<number, string>>({});
  const [loading, setLoading] = useState(true);
  const load = async () => { try { setReturns((await fetchSellerReturns()).data); } catch (error) { showToast({ kind: "error", title: "Returns unavailable", message: error instanceof Error ? error.message : "Please try again." }); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const transition = async (item: SellerReturnRequest, status: string) => { try { const response = await updateSellerReturn(item.id, status, responses[item.id]); await load(); showToast({ title: "Return updated", message: response.message }); } catch (error) { showToast({ kind: "error", title: "Return not updated", message: error instanceof Error ? error.message : "Please try again." }); } };
  return <div className="mx-auto max-w-screen-xl px-4 py-6 md:px-8 lg:px-12"><h1 className="font-[var(--font-display)] text-2xl">Returns and refunds</h1><p className="mt-1 text-sm text-[var(--color-ink-muted)]">Requests shown here belong only to your seller orders.</p>{loading ? <p className="mt-6 text-sm text-[var(--color-ink-muted)]">Loading...</p> : returns.length === 0 ? <div className="mt-6 rounded-sm border border-[var(--color-border)] bg-white p-10 text-center"><RotateCcw className="mx-auto mb-2 text-[var(--color-ink-muted)]" /><p className="text-sm text-[var(--color-ink-muted)]">No return requests.</p></div> : <div className="mt-6 space-y-4">{returns.map((item) => <article key={item.id} className="rounded-sm border border-[var(--color-border)] bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-[600]">Return #{item.id} · {item.order_number}</p><p className="mt-1 text-xs text-[var(--color-ink-muted)]">{item.buyer_name} · {item.reason.replaceAll("_", " ")}</p></div><span className="rounded-full bg-[var(--color-navy-surface)] px-3 py-1 text-xs capitalize text-[var(--color-navy)]">{item.status.replaceAll("_", " ")}</span></div><div className="mt-4 space-y-1">{item.items.map((line) => <div key={line.id} className="flex justify-between text-sm"><span>{line.product_name} × {line.quantity}</span><span>PHP {line.refund_amount.toLocaleString()}</span></div>)}</div>{item.buyer_statement && <p className="mt-3 rounded-sm bg-[var(--color-surface)] p-3 text-sm">{item.buyer_statement}</p>}{item.evidence.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{item.evidence.map((file) => <a key={file.id} href={file.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs text-[var(--color-navy)] underline">{file.name}<ExternalLink size={11} /></a>)}</div>}<textarea value={responses[item.id] ?? item.seller_response ?? ""} onChange={(event) => setResponses((current) => ({ ...current, [item.id]: event.target.value }))} rows={2} maxLength={3000} placeholder="Response to buyer" className="mt-4 w-full resize-none rounded-sm border border-[var(--color-border)] px-3 py-2 text-sm" /><div className="mt-3 flex flex-wrap justify-end gap-2">{(NEXT[item.status] ?? []).map((status) => <button key={status} onClick={() => void transition(item, status)} className="rounded-sm border border-[var(--color-navy)] px-3 py-2 text-xs font-[500] capitalize text-[var(--color-navy)] hover:bg-[var(--color-navy-surface)]">{status.replaceAll("_", " ")}</button>)}</div>{item.dispute && <p className="mt-3 text-xs font-[600] text-[var(--color-red)]">Dispute escalated: {item.dispute.status}</p>}</article>)}</div>}</div>;
}
