import { useEffect, useState } from "react";
import { downloadAdminPayoutPdf, downloadCommissionLedgerCsv, fetchAdminCommissions, fetchAdminPayout, fetchAdminPayouts, generateAdminPayout, transitionAdminPayout, type AdminPayout, type CommissionEntry } from "../../api/admin";

const money = (value: string, currency = "PHP") => new Intl.NumberFormat("en-PH", { style: "currency", currency }).format(Number(value));
const INPUT = "border border-[var(--color-border)] bg-white px-3 py-2 text-sm outline-none focus:border-[var(--color-navy)]";

export default function AdminPayoutsPage() {
  const [tab, setTab] = useState<"overview" | "seller" | "courier" | "ledger">("overview");
  const [payouts, setPayouts] = useState<AdminPayout[]>([]); const [ledger, setLedger] = useState<CommissionEntry[]>([]);
  const [summary, setSummary] = useState({ total: 0, paid: "0.00", outstanding: "0.00", pending_seller: "0.00", pending_courier: "0.00", failed_count: 0, commission_taken: "0.00", commission_pending: "0.00" }); const [page, setPage] = useState(1); const [lastPage, setLastPage] = useState(1);
  const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<AdminPayout | null>(null); const [notice, setNotice] = useState("");
  const [filterRecipient, setFilterRecipient] = useState(""); const [filterFrom, setFilterFrom] = useState(""); const [filterTo, setFilterTo] = useState(""); const [commissionType, setCommissionType] = useState("");
  const [recipientId, setRecipientId] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const recipientType = tab === "courier" ? "courier" : "seller";
  const load = () => { setNotice(""); const filters = { page, status, recipient_id: filterRecipient || undefined, from: filterFrom || undefined, to: filterTo || undefined }; if (tab === "ledger") { fetchAdminCommissions({ ...filters, commission_type: commissionType || undefined }).then((r) => { setLedger(r.data); setLastPage(r.meta.last_page) }).catch((e: Error) => setNotice(e.message)); return; } fetchAdminPayouts({ ...filters, search, recipient_type: tab === "seller" || tab === "courier" ? tab : undefined }).then((r) => { setPayouts(r.data); setSummary(r.summary); setLastPage(r.meta.last_page) }).catch((e: Error) => setNotice(e.message)); };
  useEffect(load, [tab, page, status]);
  const generate = async () => { try { const r = await generateAdminPayout({ recipient_type: recipientType, recipient_id: Number(recipientId), period_start: from, period_end: to }); setNotice(r.message); setRecipientId(""); load(); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to generate payout."); } };
  const transition = async (payout: AdminPayout, next: string) => { const payment_reference = next === "paid" ? window.prompt("Payment reference") || "" : undefined; try { const r = await transitionAdminPayout(payout.id, { status: next, payment_reference }); setNotice(r.message); setSelected(r.data); load(); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to update payout."); } };
  const open = async (id: number) => { try { setSelected((await fetchAdminPayout(id)).data); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to load payout."); } };
  const pdf = async (payout: AdminPayout) => { try { const result = await downloadAdminPayoutPdf(payout.id); const url = URL.createObjectURL(result.blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.filename || `${payout.payout_number}.pdf`; anchor.click(); URL.revokeObjectURL(url); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to download statement."); } };
  const print = async (payout: AdminPayout) => { try { const result = await downloadAdminPayoutPdf(payout.id); const url = URL.createObjectURL(result.blob); const opened = window.open(url, "_blank"); if (!opened) throw new Error("Allow pop-ups to open the printable statement."); opened.opener = null; window.setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to open printable statement."); } };
  const csv = async () => { try { const result = await downloadCommissionLedgerCsv(); const url = URL.createObjectURL(result.blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.filename || "maketo-commission-ledger.csv"; anchor.click(); URL.revokeObjectURL(url); } catch (e) { setNotice(e instanceof Error ? e.message : "Unable to export ledger."); } };
  const next: Record<string, string[]> = { draft: ["pending", "cancelled"], pending: ["approved", "withheld", "cancelled"], approved: ["processing", "withheld", "cancelled"], processing: ["paid", "failed"], failed: ["processing", "cancelled"], withheld: ["pending", "cancelled"] };
  return <div className="mx-auto max-w-screen-xl space-y-5 p-6"><div><h1 className="font-[var(--font-display)] text-2xl">Payouts & commissions</h1><p className="text-sm text-[var(--color-ink-muted)]">Versioned commission snapshots, seller settlements, and courier delivery earnings.</p></div>
    <div className="flex overflow-x-auto border-b border-[var(--color-border)]">{[["overview","Overview"],["seller","Seller payouts"],["courier","Courier payouts"],["ledger","Commission ledger"]].map(([id,label]) => <button key={id} onClick={() => { setStatus(""); setTab(id as typeof tab); setPage(1) }} className={`px-4 py-3 text-sm ${tab === id ? "border-b-2 border-[var(--color-navy)] font-semibold" : "text-[var(--color-ink-muted)]"}`}>{label}</button>)}</div>
    {notice && <p className="border border-[var(--color-border)] bg-white p-3 text-sm">{notice}</p>}
    {tab !== "ledger" && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Pending seller payouts" value={money(summary.pending_seller)}/><Card label="Pending courier payouts" value={money(summary.pending_courier)}/><Card label="Paid" value={money(summary.paid)}/><Card label="Failed payouts" value={String(summary.failed_count)}/><Card label="Platform commission earned" value={money(summary.commission_taken)}/><Card label="Commission pending" value={money(summary.commission_pending)}/><Card label="Outstanding net" value={money(summary.outstanding)}/><Card label="Payout records" value={String(summary.total)}/></div>
      {(tab === "seller" || tab === "courier") && <div className="flex flex-wrap gap-2 border border-[var(--color-border)] bg-white p-4"><input className={INPUT} placeholder={`${recipientType} ID`} inputMode="numeric" value={recipientId} onChange={(e) => setRecipientId(e.target.value.replace(/\D/g,""))}/><input className={INPUT} type="date" value={from} onChange={(e) => setFrom(e.target.value)}/><input className={INPUT} type="date" value={to} onChange={(e) => setTo(e.target.value)}/><button disabled={!recipientId || !from || !to} onClick={() => void generate()} className="bg-[var(--color-navy)] px-4 py-2 text-sm text-white disabled:opacity-50">Generate draft</button></div>}
      <div className="flex flex-wrap gap-2"><input className={`${INPUT} min-w-56 flex-1`} placeholder="Search payout or payment reference" value={search} onChange={(e) => setSearch(e.target.value)}/><input className={INPUT} placeholder="Recipient ID" value={filterRecipient} onChange={(e) => setFilterRecipient(e.target.value.replace(/\D/g,""))}/><input type="date" className={INPUT} value={filterFrom} onChange={(e) => setFilterFrom(e.target.value)}/><input type="date" className={INPUT} value={filterTo} onChange={(e) => setFilterTo(e.target.value)}/><select className={INPUT} value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }}><option value="">All statuses</option>{["draft","pending","approved","processing","paid","failed","withheld","cancelled"].map((v) => <option key={v}>{v}</option>)}</select><button className="border px-4 text-sm" onClick={load}>Apply filters</button></div>
      <div className="overflow-x-auto border border-[var(--color-border)] bg-white"><table className="w-full text-left text-sm"><thead className="bg-[var(--color-surface)]"><tr>{["Reference","Recipient","Period","Gross","Commission","Net","Status"].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{payouts.map((p) => <tr key={p.id} className="cursor-pointer border-t hover:bg-[var(--color-surface)]" onClick={() => void open(p.id)}><td className="p-3 font-medium">{p.payout_number}</td><td className="p-3">{p.recipient_name}</td><td className="p-3">{p.period_start} – {p.period_end}</td><td className="p-3">{money(p.gross_amount,p.currency)}</td><td className="p-3">{money(p.commission_amount,p.currency)}</td><td className="p-3 font-semibold">{money(p.net_amount,p.currency)}</td><td className="p-3 uppercase">{p.status}</td></tr>)}</tbody></table></div></>}
    {tab === "ledger" && <><div className="flex flex-wrap gap-2"><select className={INPUT} value={commissionType} onChange={(e) => setCommissionType(e.target.value)}><option value="">All commission types</option><option value="marketplace">Seller commission</option><option value="courier_delivery">Courier commission</option></select><select className={INPUT} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{["pending","taken","waived","reversed","refunded"].map((value) => <option key={value}>{value}</option>)}</select><input className={INPUT} placeholder="Recipient ID" value={filterRecipient} onChange={(e) => setFilterRecipient(e.target.value.replace(/\D/g,""))}/><input type="date" className={INPUT} value={filterFrom} onChange={(e) => setFilterFrom(e.target.value)}/><input type="date" className={INPUT} value={filterTo} onChange={(e) => setFilterTo(e.target.value)}/><button className="border px-4 py-2 text-sm" onClick={load}>Apply filters</button><button className="border px-4 py-2 text-sm" onClick={() => void csv()}>Export CSV</button></div><div className="overflow-x-auto border bg-white"><table className="w-full text-left text-sm"><thead><tr>{["Reference","Type","Recipient","Gross / fee","Rate","Platform commission","Recipient net","Status","Taken"].map((h) => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{ledger.map((e) => <tr className="border-t" key={e.id}><td className="p-3">{e.reference}</td><td className="p-3">{e.commission_type}</td><td className="p-3">{e.recipient_type} #{e.recipient_id}</td><td className="p-3">{money(e.gross_amount)}</td><td className="p-3">{e.percentage_rate ?? "—"}%</td><td className="p-3">{money(e.commission_amount)}</td><td className="p-3">{money(e.net_amount)}</td><td className="p-3">{e.status}</td><td className="p-3">{e.commission_taken ? "Yes" : "No"}</td></tr>)}</tbody></table></div></>}
    <div className="flex justify-end gap-2"><button disabled={page <= 1} onClick={() => setPage(page-1)} className="border px-3 py-2 text-sm disabled:opacity-40">Previous</button><span className="px-3 py-2 text-sm">{page} / {lastPage}</span><button disabled={page >= lastPage} onClick={() => setPage(page+1)} className="border px-3 py-2 text-sm disabled:opacity-40">Next</button></div>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={() => setSelected(null)}><div className="max-h-[90vh] w-full max-w-3xl overflow-auto bg-white p-5" onClick={(e) => e.stopPropagation()}><div className="flex justify-between"><div><h2 className="text-lg font-semibold">{selected.payout_number}</h2><p className="text-sm text-[var(--color-ink-muted)]">{selected.recipient_name} · {selected.status}</p></div><button onClick={() => setSelected(null)}>Close</button></div><div className="my-4 grid grid-cols-3 gap-3"><Card label="Gross" value={money(selected.gross_amount)}/><Card label="Commission" value={money(selected.commission_amount)}/><Card label="Net" value={money(selected.net_amount)}/></div><div className="space-y-2">{selected.items?.map((i) => <div key={i.id} className="flex justify-between border p-3 text-sm"><span>{i.description}</span><strong>{money(i.net_amount)}</strong></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => void print(selected)} className="border px-3 py-2 text-sm">Print A4</button><button onClick={() => void pdf(selected)} className="border px-3 py-2 text-sm">Download A4 PDF</button>{(next[selected.status] || []).map((s) => <button key={s} onClick={() => void transition(selected,s)} className="bg-[var(--color-navy)] px-3 py-2 text-sm text-white">Mark {s}</button>)}</div></div></div>}
  </div>;
}
function Card({label,value}:{label:string;value:string}) { return <div className="border border-[var(--color-border)] bg-white p-4"><p className="text-xs text-[var(--color-ink-muted)]">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div> }
