import { useEffect, useState } from "react"
import { ArrowLeft, Search } from "lucide-react"
import { Link } from "react-router"
import { fetchAdminActivity, type AdminActivity, type PaginationMeta } from "../../api/admin"

export default function AdminActivityPage() {
  const [activity, setActivity] = useState<AdminActivity[]>([]); const [meta, setMeta] = useState<PaginationMeta | null>(null)
  const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [category, setCategory] = useState(""); const [eventType, setEventType] = useState(""); const [source, setSource] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState("")
  const [page, setPage] = useState(1); const [perPage, setPerPage] = useState(25); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [selected, setSelected] = useState<AdminActivity | null>(null)
  useEffect(() => { let mounted = true; setLoading(true); setError(null); const timer = window.setTimeout(() => { fetchAdminActivity({ search, role, category, event_type: eventType, source, from, to, page, per_page: perPage }).then((response) => { if (mounted) { setActivity(response.data); setMeta(response.meta) } }).catch((reason: Error) => mounted && setError(reason.message)).finally(() => mounted && setLoading(false)) }, 250); return () => { mounted = false; window.clearTimeout(timer) } }, [search, role, category, eventType, source, from, to, page, perPage])
  const resetPage = (update: () => void) => { update(); setPage(1) }

  return <div className="mx-auto max-w-screen-xl p-4 md:p-6"><header className="mb-6"><Link to="/admin/analytics?tab=security" className="mb-3 inline-flex items-center gap-1 text-xs font-semibold text-[var(--color-navy)]"><ArrowLeft size={14}/> Back to Security analytics</Link><h1 className="font-[var(--font-display)] text-2xl text-[var(--color-navy)] md:text-3xl">Platform Activity</h1><p className="mt-1 text-sm text-[var(--color-ink-muted)]">Live audit events and trustworthy reconstructed marketplace history</p></header>
    <section className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-black/[0.05]"><div className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-2 xl:grid-cols-4"><label className="relative"><Search size={15} className="absolute left-3 top-2.5 text-slate-400"/><input value={search} onChange={(event) => resetPage(() => setSearch(event.target.value))} placeholder="Search activity" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-[var(--color-navy)]"/></label><Filter value={role} setValue={(value) => resetPage(() => setRole(value))} label="All roles" options={["admin", "seller", "buyer"]}/><Filter value={category} setValue={(value) => resetPage(() => setCategory(value))} label="All categories" options={["authentication", "user", "seller", "catalog", "order", "commerce", "operations", "moderation", "settings"]}/><input value={eventType} onChange={(event) => resetPage(() => setEventType(event.target.value))} placeholder="Event type" className="rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-[var(--color-navy)]"/><Filter value={source} setValue={(value) => resetPage(() => setSource(value))} label="All sources" options={["audit_log", "historical_record"]}/><input type="date" value={from} onChange={(event) => resetPage(() => setFrom(event.target.value))} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" aria-label="From date"/><input type="date" min={from || undefined} value={to} onChange={(event) => resetPage(() => setTo(event.target.value))} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" aria-label="To date"/></div>
      {error && <p className="m-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-[var(--color-ink-muted)]"><tr><th className="p-3">Timestamp</th><th className="p-3">Actor</th><th className="p-3">Role</th><th className="p-3">Activity</th><th className="p-3">Category</th><th className="p-3">Source</th><th className="p-3"></th></tr></thead><tbody>{activity.map((entry) => <tr key={entry.id} className="border-t border-slate-100"><td className="whitespace-nowrap p-3 text-xs text-[var(--color-ink-muted)]">{new Date(entry.occurred_at).toLocaleString()}</td><td className="p-3 font-medium">{entry.user?.name ?? "System / unknown"}</td><td className="p-3 capitalize">{entry.role ?? "—"}</td><td className="p-3"><p>{entry.description}</p><p className="text-xs text-[var(--color-ink-muted)]">{entry.event_type}</p></td><td className="p-3 capitalize">{entry.category}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{entry.source_label}</span></td><td className="p-3"><button onClick={() => setSelected(entry)} className="text-xs font-semibold text-[var(--color-navy)]">Details</button></td></tr>)}</tbody></table>{loading && <p className="p-8 text-center text-sm text-[var(--color-ink-muted)]">Loading platform activity...</p>}{!loading && !activity.length && <p className="p-8 text-center text-sm text-[var(--color-ink-muted)]">No activity matches these filters.</p>}</div>
      {meta && <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 p-4 text-xs text-[var(--color-ink-muted)]"><span>{meta.total} events · Page {meta.current_page} of {meta.last_page}</span><div className="flex gap-2"><select value={perPage} onChange={(event) => resetPage(() => setPerPage(Number(event.target.value)))} className="rounded-lg border border-slate-200 px-2"><option>25</option><option>50</option><option>100</option></select><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={page >= meta.last_page} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Next</button></div></footer>}
    </section>{selected && <ActivityDetail entry={selected} close={() => setSelected(null)}/>}</div>
}

function Filter({ value, setValue, label, options }: { value: string; setValue: (value: string) => void; label: string; options: string[] }) { return <select value={value} onChange={(event) => setValue(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-[var(--color-navy)]"><option value="">{label}</option>{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select> }
function ActivityDetail({ entry, close }: { entry: AdminActivity; close: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={close}><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl" onClick={(event) => event.stopPropagation()}><div className="mb-5 flex justify-between"><h2 className="font-[var(--font-display)] text-lg">Activity details</h2><button onClick={close} className="text-sm">Close</button></div><dl className="grid grid-cols-[105px_1fr] gap-3 text-sm"><dt className="text-[var(--color-ink-muted)]">Timestamp</dt><dd>{new Date(entry.occurred_at).toLocaleString()}</dd><dt className="text-[var(--color-ink-muted)]">Actor</dt><dd>{entry.user?.name ?? "System / unknown"}</dd><dt className="text-[var(--color-ink-muted)]">Role</dt><dd>{entry.role ?? "—"}</dd><dt className="text-[var(--color-ink-muted)]">Action</dt><dd>{entry.event_type}</dd><dt className="text-[var(--color-ink-muted)]">Target</dt><dd>{entry.target ? `${entry.target.type} #${entry.target.id}` : "—"}</dd><dt className="text-[var(--color-ink-muted)]">IP</dt><dd>{entry.ip_address ?? "Not captured"}</dd><dt className="text-[var(--color-ink-muted)]">User agent</dt><dd className="break-all">{entry.user_agent ?? "Not captured"}</dd><dt className="text-[var(--color-ink-muted)]">Source</dt><dd>{entry.source_label} ({entry.source_table})</dd></dl></div></div> }
