import { useEffect, useState } from "react";
import { Search, X } from "lucide-react";
import { fetchAdminUsers, updateAdminUserStatus, type AdminUser } from "../../api/admin";
import { StatusBadge } from "../../components/admin/StatusBadge";

const money = (value: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(value);
const date = (value: string | null) => value ? new Date(value).toLocaleString("en-PH") : "Not available";

export default function UserManagementPage() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [selected, setSelected] = useState<AdminUser | null>(null);
  const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [reason, setReason] = useState("");

  useEffect(() => { let active = true; const timer = window.setTimeout(() => { setLoading(true); setError(null); fetchAdminUsers({ search, role, status, per_page: 100 }).then(response => { if (active) setUsers(response.data); }).catch((caught: Error) => { if (active) setError(caught.message); }).finally(() => { if (active) setLoading(false); }); }, 250); return () => { active = false; window.clearTimeout(timer); }; }, [search, role, status]);

  const changeStatus = async (nextStatus: string) => { if (!selected) return; if (nextStatus !== "active" && reason.trim().length < 5) { setError("Enter a reason with at least 5 characters."); return; } setSaving(true); setError(null); try { const response = await updateAdminUserStatus(selected.id, nextStatus, reason.trim() || undefined); setUsers(current => current.map(user => user.id === selected.id ? response.data : user)); setSelected(response.data); setReason(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update the user."); } finally { setSaving(false); } };

  return <div className="flex h-full min-h-[calc(100vh-56px)]">
    <div className={`flex-1 ${selected ? "hidden lg:block" : "block"}`}><header className="p-5 border-b border-[var(--color-border)] bg-white"><h1 className="font-[var(--font-display)] text-xl mb-3">Users</h1><div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 flex-1 min-w-52 border border-[var(--color-border)] px-3 py-2 bg-[var(--color-surface)]"><Search size={14} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name, email, mobile" className="bg-transparent outline-none text-sm w-full" /></label><select value={role} onChange={event => setRole(event.target.value)} className="border border-[var(--color-border)] px-3 text-sm"><option value="">All roles</option><option value="buyer">Buyer</option><option value="seller">Seller</option><option value="admin">Admin</option></select><select value={status} onChange={event => setStatus(event.target.value)} className="border border-[var(--color-border)] px-3 text-sm"><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="restricted">Restricted</option></select></div></header>
      {loading && <p className="p-8 text-sm text-[var(--color-ink-muted)]">Loading users...</p>}{error && <p className="m-5 p-3 bg-[var(--color-red-light)] text-[var(--color-red)] text-sm">{error}</p>}{!loading && !error && users.length === 0 && <p className="p-8 text-sm text-[var(--color-ink-muted)]">No users match these filters.</p>}
      {!loading && users.length > 0 && <div className="overflow-x-auto"><table className="w-full bg-white"><thead className="bg-[var(--color-surface)] text-left text-xs text-[var(--color-ink-muted)]"><tr><th className="p-3">User</th><th>Role</th><th>Status</th><th>Orders</th><th>Spent</th><th>Last active</th></tr></thead><tbody>{users.map(user => <tr key={user.id} onClick={() => setSelected(user)} className="border-b border-[var(--color-border-subtle)] hover:bg-[var(--color-surface)] cursor-pointer"><td className="p-3"><p className="text-sm font-[500]">{user.name}</p><p className="text-xs text-[var(--color-ink-muted)]">{user.email}</p></td><td className="text-xs capitalize">{user.role}</td><td className="text-xs"><StatusBadge status={user.status} /></td><td className="text-xs">{user.orders}</td><td className="text-xs">{money(user.total_spent)}</td><td className="text-xs text-[var(--color-ink-muted)]">{date(user.last_active_at)}</td></tr>)}</tbody></table></div>}
    </div>
    {selected && <aside className="w-full lg:w-96 border-l border-[var(--color-border)] bg-white"><div className="p-5 border-b border-[var(--color-border)] flex justify-between"><div><h2 className="font-[600]">{selected.name}</h2><p className="text-xs text-[var(--color-ink-muted)]">{selected.email}</p></div><button onClick={() => setSelected(null)}><X size={16} /></button></div><div className="p-5 space-y-3 text-sm">{[["User ID", selected.id], ["Mobile", selected.mobile], ["Location", selected.location ?? "Not provided"], ["Role", selected.role], ["Status", selected.status], ["Verified", selected.verified ? "Yes" : "No"], ["Joined", date(selected.joined_at)], ["Orders", selected.orders], ["Total spent", money(selected.total_spent)]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-[var(--color-border-subtle)] pb-2"><span className="text-[var(--color-ink-muted)]">{label}</span><span className="text-right capitalize">{label === "Status" ? <StatusBadge status={String(value)} /> : value}</span></div>)}<textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Reason required for restriction" className="w-full border border-[var(--color-border)] p-2 text-sm" rows={3} /><div className="flex flex-wrap gap-2"><button disabled={saving} onClick={() => void changeStatus("active")} className="px-3 py-2 bg-[var(--color-green)] text-white text-xs disabled:opacity-50">Activate</button><button disabled={saving} onClick={() => void changeStatus("suspended")} className="px-3 py-2 bg-[var(--color-amber)] text-white text-xs disabled:opacity-50">Suspend</button><button disabled={saving} onClick={() => void changeStatus("restricted")} className="px-3 py-2 bg-[var(--color-red)] text-white text-xs disabled:opacity-50">Restrict</button></div></div></aside>}
  </div>;
}
